// <auto-generated/>
#nullable enable

namespace PolyBot;
/// <summary>
/// Hosted-service long polling: starts <c>ReceiveAsync</c> in the background on
/// start (after deleting any stale webhook) and signals a cancellation token on
/// stop, awaiting the polling loop's completion.
/// </summary>
public sealed class PolyBotPollingHostedService : global::Microsoft.Extensions.Hosting.IHostedService
{
    private readonly global::Telegram.Bot.ITelegramBotClient _botClient;
    private readonly global::Telegram.Bot.Polling.IUpdateHandler _updateHandler;
    private readonly global::Telegram.Bot.Polling.ReceiverOptions _receiverOptions;
    private readonly global::PolyBot.PolyBotOptions _options;
    private readonly global::System.Threading.CancellationTokenSource _stoppingCts = new global::System.Threading.CancellationTokenSource();
    private global::System.Threading.Tasks.Task? _pollingTask;
    public PolyBotPollingHostedService(global::Telegram.Bot.ITelegramBotClient botClient, global::PolyBot.PolyBotOptions options, global::Telegram.Bot.Polling.IUpdateHandler updateHandler, global::Telegram.Bot.Polling.ReceiverOptions? receiverOptions = null)
    {
        _botClient = botClient;
        _options = options;
        _updateHandler = updateHandler;
        _receiverOptions = receiverOptions ?? new global::Telegram.Bot.Polling.ReceiverOptions();
    }

    public async global::System.Threading.Tasks.Task StartAsync(global::System.Threading.CancellationToken cancellationToken)
    {
        global::Telegram.Bot.Types.User me = await global::Telegram.Bot.TelegramBotClientExtensions.GetMe(_botClient!, cancellationToken).ConfigureAwait(false);
        if (!string.IsNullOrEmpty(me.Username))
        {
            _options.BotUsername = me.Username;
        }

        _pollingTask = global::System.Threading.Tasks.Task.Run(PollAsync, global::System.Threading.CancellationToken.None);
    }

    public async global::System.Threading.Tasks.Task StopAsync(global::System.Threading.CancellationToken cancellationToken)
    {
        _stoppingCts.Cancel();
        if (_pollingTask is not null)
        {
            await global::System.Threading.Tasks.Task.WhenAny(_pollingTask, global::System.Threading.Tasks.Task.Delay(global::System.Threading.Timeout.Infinite, cancellationToken)).ConfigureAwait(false);
        }
    }

    private async global::System.Threading.Tasks.Task PollAsync()
    {
        await global::Telegram.Bot.TelegramBotClientExtensions.DeleteWebhook(_botClient, _receiverOptions.DropPendingUpdates, _stoppingCts.Token).ConfigureAwait(false);
        await global::Telegram.Bot.TelegramBotClientExtensions.ReceiveAsync(_botClient, _updateHandler, _receiverOptions, _stoppingCts.Token).ConfigureAwait(false);
    }
}

/// <summary>
/// DI registration for hosted-service long polling.
/// </summary>
public static class PolyBotHostingExtensions
{
    /// <summary>
    /// Registers the router and a <c>PolyBotPollingHostedService</c> that long-polls
    /// updates in the background.
    /// </summary>
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddPolyBotHostedPolling(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services, global::System.Action<global::Telegram.Bot.Polling.ReceiverOptions>? configureReceiver = null)
    {
        global::PolyBot.PolyBotExtensions.AddPolyBotRouter(services);
        global::Telegram.Bot.Polling.ReceiverOptions receiverOptions = new global::Telegram.Bot.Polling.ReceiverOptions();
        if (configureReceiver is not null)
        {
            configureReceiver(receiverOptions);
        }

        receiverOptions.AllowedUpdates ??= global::PolyBot.BotRouter.AllowedUpdates;
        global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton(services, receiverOptions);
        global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton<global::Microsoft.Extensions.Hosting.IHostedService>(services, static (global::System.IServiceProvider sp) => new global::PolyBot.PolyBotPollingHostedService(global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Telegram.Bot.ITelegramBotClient>(sp), global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService<global::PolyBot.PolyBotOptions>(sp) ?? new global::PolyBot.PolyBotOptions(), global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Telegram.Bot.Polling.IUpdateHandler>(sp), global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService<global::Telegram.Bot.Polling.ReceiverOptions>(sp)));
        return services;
    }
}