// <auto-generated/>
#nullable enable

namespace PolyBot;
/// <summary>
/// Sets the webhook on startup (when a <see cref="T:PolyBot.PolyBotOptions"/> is
/// registered) and optionally deletes it on graceful shutdown.
/// </summary>
public sealed class PolyBotWebhookHostedService : global::Microsoft.Extensions.Hosting.IHostedService
{
    private readonly global::Telegram.Bot.ITelegramBotClient _botClient;
    private readonly global::Telegram.Bot.Polling.IUpdateHandler _updateHandler;
    private readonly global::PolyBot.PolyBotOptions _options;
    public PolyBotWebhookHostedService(global::Telegram.Bot.ITelegramBotClient botClient, global::Telegram.Bot.Polling.IUpdateHandler updateHandler, global::PolyBot.PolyBotOptions options)
    {
        _botClient = botClient;
        _updateHandler = updateHandler;
        _options = options;
    }

    public async global::System.Threading.Tasks.Task StartAsync(global::System.Threading.CancellationToken cancellationToken)
    {
        if (string.IsNullOrEmpty(_options.WebhookUrl))
        {
            throw new global::System.InvalidOperationException("PolyBotOptions.WebhookUrl must be set to an absolute HTTPS URL to receive webhook updates.");
        }

        global::Telegram.Bot.Types.User me = await global::Telegram.Bot.TelegramBotClientExtensions.GetMe(_botClient!, cancellationToken).ConfigureAwait(false);
        if (!string.IsNullOrEmpty(me.Username))
        {
            _options.BotUsername = me.Username;
        }

        await global::Telegram.Bot.TelegramBotClientExtensions.SetWebhook(_botClient, _options.WebhookUrl, null, null, _options.WebhookMaxConnections, _options.AllowedUpdates, _options.DropPendingUpdates, _options.WebhookSecretToken, cancellationToken).ConfigureAwait(false);
    }

    public async global::System.Threading.Tasks.Task StopAsync(global::System.Threading.CancellationToken cancellationToken)
    {
        if (_options.DeleteWebhookOnStop)
        {
            await global::Telegram.Bot.TelegramBotClientExtensions.DeleteWebhook(_botClient, _options.DropPendingUpdates, cancellationToken).ConfigureAwait(false);
        }
    }
}

/// <summary>
/// DI registration and endpoint mapping for the ASP.NET Core webhook
/// integration: secret-token verification, direct stream deserialization and
/// hand-off to the generated router.
/// </summary>
public static class PolyBotWebhookExtensions
{
    /// <summary>
    /// Registers the router and the configured <see cref="T:PolyBot.PolyBotOptions"/>;
    /// when hosting abstractions are referenced, a <c>PolyBotWebhookHostedService</c> that
    /// sets the webhook on startup is registered too.
    /// </summary>
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddPolyBotWebhook(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services, global::System.Action<global::PolyBot.PolyBotOptions>? configure = null)
    {
        global::PolyBot.PolyBotExtensions.AddPolyBotRouter(services);
        if (configure is not null)
        {
            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton(services, new ConfigureHolder(configure));
        }

        global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton<global::Microsoft.Extensions.Hosting.IHostedService>(services, (global::System.IServiceProvider sp) =>
        {
            global::PolyBot.PolyBotOptions options = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService<global::PolyBot.PolyBotOptions>(sp) ?? new global::PolyBot.PolyBotOptions();
            ConfigureHolder? holder = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService<ConfigureHolder>(sp);
            if (holder is not null)
            {
                holder.Configure(options);
            }

            return new global::PolyBot.PolyBotWebhookHostedService(global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Telegram.Bot.ITelegramBotClient>(sp), global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Telegram.Bot.Polling.IUpdateHandler>(sp), options);
        });
        return services;
    }

    /// <summary>
    /// Maps a POST endpoint that verifies the secret token, deserializes the update
    /// from the request body and feeds it into the generated router.
    /// </summary>
    public static global::Microsoft.AspNetCore.Builder.IEndpointConventionBuilder MapPolyBotWebhook(this global::Microsoft.AspNetCore.Builder.IEndpointRouteBuilder endpoints, string pattern = "/bot")
    {
        return global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapPost(endpoints, pattern, (global::Microsoft.AspNetCore.Http.RequestDelegate)HandlePolyBotWebhookAsync);
    }

    /// <summary>
    /// Request delegate: secret-token verification (missing header 400, wrong value
    /// 401), direct body-stream deserialization, router hand-off, 200 OK.
    /// </summary>
    private static async global::System.Threading.Tasks.Task HandlePolyBotWebhookAsync(global::Microsoft.AspNetCore.Http.HttpContext context)
    {
        global::PolyBot.PolyBotOptions options = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService<global::PolyBot.PolyBotOptions>(context.RequestServices) ?? new global::PolyBot.PolyBotOptions();
        ConfigureHolder? endpointHolder = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService<ConfigureHolder>(context.RequestServices);
        if (endpointHolder is not null)
        {
            endpointHolder.Configure(options);
        }
        if (options.WebhookSecretToken is not null)
        {
            if (!context.Request.Headers.TryGetValue("X-Telegram-Bot-Api-Secret-Token", out global::Microsoft.Extensions.Primitives.StringValues __curator_secretValues))
            {
                context.Response.StatusCode = 400;
                return;
            }

            if (__curator_secretValues.Count != 1 || !string.Equals(options.WebhookSecretToken, __curator_secretValues[0], global::System.StringComparison.Ordinal))
            {
                context.Response.StatusCode = 401;
                return;
            }
        }

        global::Telegram.Bot.Types.Update? update;
        try
        {
            update = await global::System.Text.Json.JsonSerializer.DeserializeAsync(context.Request.Body, global::Telegram.Bot.JsonBotSerializerContext.Default.Update, context.RequestAborted).ConfigureAwait(false);
        }
        catch (global::System.Text.Json.JsonException)
        {
            context.Response.StatusCode = 400;
            return;
        }

        if (update is not { Id: > 0 })
        {
            context.Response.StatusCode = 400;
            return;
        }

        global::Telegram.Bot.Polling.IUpdateHandler handler = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Telegram.Bot.Polling.IUpdateHandler>(context.RequestServices);
        global::Telegram.Bot.ITelegramBotClient botClient = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Telegram.Bot.ITelegramBotClient>(context.RequestServices);
        await handler.HandleUpdateAsync(botClient, update, context.RequestAborted).ConfigureAwait(false);
        context.Response.StatusCode = 200;
    }

    private sealed class ConfigureHolder
    {
        public ConfigureHolder(global::System.Action<global::PolyBot.PolyBotOptions> configure)
        {
            Configure = configure;
        }

        public global::System.Action<global::PolyBot.PolyBotOptions> Configure { get; }
    }
}