using Telegram.Bot.Types.Enums;

namespace PolyBot;

/// <summary>
/// Provides the compile-time-inferred <c>AllowedUpdates</c> array generated by the PolyBot source generator.
/// </summary>
public interface IAllowedUpdatesProvider
{
    /// <summary>
    /// The exact set of <see cref="UpdateType"/> values the bot is configured to receive.
    /// </summary>
    UpdateType[] AllowedUpdates { get; }
}
