using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace PolyBot.SourceGenerators;

/// <summary>
/// Normalizes a syntax tree and post-processes the text into the repo "pretty brackets" style.
/// </summary>
internal static class GeneratedSource
{
    private const string Header = "// <auto-generated/>";
    private const string NewLine = "\r\n";

    public static string Render(CompilationUnitSyntax compilationUnit)
    {
        string body = compilationUnit.NormalizeWhitespace().ToFullString();
        return Header + NewLine +
               "#nullable enable" + NewLine +
               NewLine +
               body;
    }
}
